Tests with sky-based calibration
pykoala/pykoala pull request #502
Opened 2024-11-19 23:05 UTC by paranoya

Although my tests focused on WEAVE QA (hence the misleading name of the branch), they are also useful for KOALA data

2024-11-20 05:17 UTC, miguelglezb requested changes
twilight_weave.py is generating

2024-11-20 05:17 UTC, miguelglezb commented on tutorials/corrections/sky-based_calibration.ipynb
> +   "version": "3.8.10"
We need to talk about the supported Python versions...

2024-11-20 05:17 UTC, miguelglezb commented on test/twighlight_weave.py
Why is this script testing?

2024-11-20 05:17 UTC, miguelglezb commented on test/twighlight_weave.py
> +science_rss = koala_rss("/home/pcorchoc/Develop/pykoala-tutorials/tutorials/data/koala/580V/27feb10035red.fits")
This path is from a local machine, it may not work on the repository.

2024-11-26 22:51 UTC, miguelglezb approved these changes

2024-11-27 08:07 UTC, PabloCorcho commented on src/pykoala/corrections/sky.py
>          b = I_low - m * flux_low
This is not very PEPOCHO :smile:

2024-11-27 08:08 UTC, PabloCorcho commented on src/pykoala/corrections/sky.py
> +    def __init__(self, rss: RSS, h=None):
I know time is precious these days, but we need to document the code.

2024-11-27 08:15 UTC, PabloCorcho approved these changes

2024-11-27 08:15 UTC, PabloCorcho commented on src/pykoala/corrections/wavelength.py
> +        vprint(f'Solar spectrum from {path}')
this should be `self.vprint`

2024-11-27 08:15 UTC, PabloCorcho commented on src/pykoala/data_container.py
> +        assert ('fibre_diameter' in kwargs)
Maybe we need to rethink the way we check the arguments. I do not like the idea of having these many asserts...

2024-11-27 08:15 UTC, PabloCorcho commented on test/twighlight_weave.py
Shall we create yet another directory called `dev_testing` or something similar, that is not included in the MANIFEST, solely devoted for sharing scripts to test stuff?

2024-11-28 23:30 UTC, miguelglezb commented on test/twighlight_weave.py
I'm not sure something like that is necessary at this stage. Furthermore, I still fail to see what this script is testing. I can see it creates some plots, but it would be nice if we could check that the values in the plots make sense. For example, 
```python
assert all(science_rss.wavelength > 0)
```
and maybe save the plot in a tmp directory. After that, checking that the file of the plot exists and has a minimum size (in case the plot was not done correctly)

```python
import os

file_path = "path/to/plot.png"
expected_size = 1024 #This can be checked by creating the plot beforehand
file_size = os.path.getsize(file_path)

assert os.path.exists(file_path), "Plot not found"  
assert file_size > expected_size, "Plot file has smaller size than expected"
``` 

This second part of the test requires fixtures in order to create the tmp directory, but it shouldn't be hard to implement since we already using them in the unit tests.

2024-11-28 23:45 UTC, miguelglezb reviewed
`test/twighlight_weave.py` is missing the test.

2025-04-17 21:43 UTC, closed without merging

2025-04-17 21:43 UTC, paranoya commented
I think this PR is clearly outdated. Let me please close it.